datasource:
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jdbcUrl: jdbc:log4jdbc:oracle:thin:@//
  username: 
  password: 
  maximumpoolsize: 10
  auto-commit: false
  cacheprepstmts: true
  prepstmtcachesize: 250
  prepstmtcachesqlLimit: 2048
  
